### ISSUE TITLE
Example of issue

### ISSUE THREAD

**Issue by simonmasson** [mtherun/Finite-volume-method#2]
This is an example of issue for @mtherun in order to understand the concept of issue.

What is nice is that you can use Markdown, for writing nice stuffs.

Here are some tasks for you:
- [x] Offer some massala spices to @simonmasson
- [x] Write a comment below this issue,
- [x] Assign @simonmasson to this issue,
- [x] Close the issue.

**Comment by monishamuralidharanm** [comment]
Ahah!
I'm sure I got the second one down to go.
Who's the best?
- [ ]  Monisha

- [ ] Monisha again

- [ ]  Not @simonmasson xD

**Comment by monishamuralidharanm** [comment]
Thank you simon, this is awesome!
